"ENV_NAME": "overcooked_v2"
"ENV_KWARGS": 
  "layout" : "grounded_coord_simple"
  "agent_view_size": 2
  "negative_rewards": True
  "sample_recipe_on_delivery": True
  "random_agent_positions": True

"LR": 5e-4
"ANNEAL_LR": True
"LR_WARMUP": 0.05

"NUM_ENVS": 256
"NUM_STEPS": 256
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 64

"TOTAL_TIMESTEPS": 2e7
"REW_SHAPING_HORIZON": 1e7

"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128

"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"SCALE_CLIP_EPS": False
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.25
"ACTIVATION": "relu"
"SEED": 0
"NUM_SEEDS": 1

# WandB Params
"ENTITY": "tobiges"
"PROJECT": "jaxmarl-overcooked"
"WANDB_MODE" : "online"
